-- (1) JOIN
-- ANIMAL_INS 테이블에 해당하는 값만 찾아서 정렬 후 3개로 제한
SELECT
       I.NAME
     , I.DATETIME
  FROM ANIMAL_INS I
  LEFT OUTER JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
 WHERE O.ANIMAL_ID IS NULL
 ORDER BY I.DATETIME
 LIMIT 3;


-- (2) String, Date
-- 두 테이블을 INNER JOIN하여 겹치는 값 중 (입양일 - 보호시작일)이 가장 큰 값 2개를 찾음
SELECT
       O.ANIMAL_ID
     , O.NAME
  FROM ANIMAL_OUTS O
  INNER JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
 ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
 LIMIT 2;