
-- Revising the Select Query I
-- 인구가 100000 이상이면서 국가코드가 USA
SELECT * FROM CITY WHERE POPULATION >= 100000 AND CountryCode = 'USA';

-- Select All
SELECT * FROM CITY;
SELECT ID, NAME, COUNTRYCODE, DISTRICT, POPULATION FROM CITY;

-- Select By ID
SELECT ID, NAME, COUNTRYCODE, DISTRICT, POPULATION FROM CITY WHERE ID = 1661;

-- Japanese Cities' Attributes
SELECT ID, NAME,  COUNTRYCODE, DISTRICT, POPULATION FROM CITY WHERE COUNTRYCODE = 'JPN';

-- Japanese Cities' Names
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'JPN';

-- Weather Observation Station 1
SELECT CITY, STATE FROM STATION;