
-- Weather Observation Station 4
SELECT 
       COUNT(CITY) - COUNT(DISTINCT CITY)
  FROM STATION

-- Weather Observation Station 5
-- 시도 -> ERROR 1140 (42000)
SELECT 
       CONCAT(CITY, ' ', MIN(LENGTH(CITY)))
     , CONCAT(CITY, ' ', MAX(LENGTH(CITY)))
  FROM STATION
 ORDER BY CITY;
--
SELECT 
       CITY
     , LENGTH(CITY)
  FROM STATION
 ORDER BY LENGTH(CITY) ASC, CITY ASC
 LIMIT 1;
 
SELECT CITY
     , LENGTH(CITY)
  FROM STATION
 ORDER BY LENGTH(CITY) DESC, CITY ASC
 LIMIT 1

-- 서브쿼리 풀이)
SELECT 
       CITY
     , LENGTH(CITY)
  FROM STATION
 WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
 ORDER BY CITY
 LIMIT 1;

SELECT 
       CITY
     , LENGTH(CITY)
  FROM STATION
 WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
 ORDER BY CITY
 LIMIT 1

-- UNION 풀이)
(SELECT 
       CITY
     , LENGTH(CITY)
  FROM STATION
 WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
 ORDER BY CITY
 LIMIT 1)
UNION ALL
(SELECT 
       CITY
     , LENGTH(CITY)
  FROM STATION
 WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
 ORDER BY CITY
 LIMIT 1)