-- 1
-- 범위 JOIN
SELECT S.ID
     , S.NAME
     , S.MARKS
     , G.GRADE
  FROM STUDENTS S
 INNER JOIN GRADES G ON G.MIN_MARK <= S.MARKS AND S.MARKS <= G.MAX_MARK;

-- 2
-- GRADE가 8 미만이면 NAEM은 NULL로 출력
SELECT (CASE WHEN G.GRADE < 8 THEN 'NULL' ELSE S.NAME END) AS NAME
     , S.MARKS
     , G.GRADE
  FROM STUDENTS S
 INNER JOIN GRADES G ON G.MIN_MARK <= S.MARKS AND S.MARKS <= G.MAX_MARK;

-- 3
SELECT (CASE 
            WHEN G.GRADE < 8 THEN CONCAT('NULL', ' (grade ', G.GRADE, ')') 
            ELSE CONCAT(S.NAME, ' (grade ', G.GRADE, ')') 
        END) 
  FROM STUDENTS S
 INNER JOIN GRADES G ON G.MIN_MARK <= S.MARKS AND S.MARKS <= G.MAX_MARK;

-- 정답
SELECT (CASE 
            WHEN G.GRADE < 8 THEN 'NULL'
            ELSE S.NAME
        END)
     , G.GRADE
     , S.MARKS
  FROM STUDENTS S
 INNER JOIN GRADES G ON G.MIN_MARK <= S.MARKS AND S.MARKS <= G.MAX_MARK
 ORDER BY G.GRADE DESC, S.NAME ASC, S.MARKS ASC;